### ISSUE TITLE
paper is accepted by?????accv?    where is the code of the iou-uniform??

### ISSUE THREAD

**Issue by henbucuoshanghai** [zl1994/IoU-Uniform-R-CNN#1]

**Comment by zl1994** [comment]
This paper is under review by a journal. https://github.com/zl1994/IoU-Uniform-R-CNN/blob/f834f9fefd2d2fbfb8db91657c09bf72bf2e9767/mmdet/models/detectors/two_stage.py#L237 is where we generate training samples with uniform IoU distribution. You can find more details when you run and read the codes.
