### ISSUE TITLE
something about train 

### ISSUE THREAD

**Issue by pipi2020** [zl1994/IoU-Uniform-R-CNN#2]
i am sorry to tell you about this error.
could you tell me how to solve 'TypeError: loss() got an unexpected keyword argument 'IoU_rank'
i watch the code ,but i am not find the  keyword in loss()
if you can tell me ,i would be greatful

**Comment by pipi2020** [comment]
@zl1994

**Comment by zl1994** [comment]
Sorry for the mistake. You can just delete the input arg "IoU_rank=True"

**Comment by pipi2020** [comment]
Thank you very much for your reply I've tried as you say . But unfortunately, When I run demo, There's another mistake.  “SharedFCBBoxHead”has no attribute “get_final_det_bboxes”，so I don't know where the problem is. Please help me to solve it. Thank you very much?------------------ 原始邮件 ------------------
发件人: "Li Zhu"<notifications@github.com>
发送时间: 2019年12月20日(星期五) 上午8:58
收件人: "zl1994/IoU-Uniform-R-CNN"<IoU-Uniform-R-CNN@noreply.github.com>;
抄送: "pipi"<787117010@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zl1994/IoU-Uniform-R-CNN] something about train  (#2)



Sorry for the mistake. You can just delete the input arg "IoU_rank=True"
 
&mdash;

**Comment by zl1994** [comment]
Which demo？Please tell me exactly where the error occurred.

**Comment by pipi2020** [comment]
or could you send me a demo file so that i can test the model i have trained with visualization. thank you .------------------ 原始邮件 ------------------
发件人: "Li Zhu"<notifications@github.com>
发送时间: 2019年12月20日(星期五) 中午11:47
收件人: "zl1994/IoU-Uniform-R-CNN"<IoU-Uniform-R-CNN@noreply.github.com>;
抄送: "pipi"<787117010@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zl1994/IoU-Uniform-R-CNN] something about train  (#2)



Which demo？Please tell me exactly where the error occurred.
 
&mdash;

**Comment by pipi2020** [comment]
the demo file is in mmdetection which is used for testing the trained model file with  visualization
as follows:

from mmdet.apis import init_detector, inference_detector, show_result
import mmcv

config_file = 
'/media/pipi/新加卷/IoU-Uniform-R-CNN/configs/cascade_rcnn_r101_fpn_IoU_reg_1x.py'
checkpoint_file =
 '/media/pipi/新加卷/IoU-Uniform-R-CNN/work_dirs/cascade_rcnn_r101_fpn_1x_IoU_reg-HFUT-80/latest.pth'  

model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = mmcv.imread('/media/pipi/新加卷/IoU-Uniform-R-CNN/data/HFUT/2/HFUT_000009.jpg')
result = inference_detector(model, img)
show_result(img, result, model.CLASSES)


but there is an error i can not solve:

Traceback (most recent call last):
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/demo/demo.py", line 38, in <module>
    result = inference_detector(model, img)
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/mmdet/apis/inference.py", line 86, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/media/pipi/新加卷/anaconda3/envs/IoU-Uniform-R-CNN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/mmdet/models/detectors/base.py", line 127, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/mmdet/models/detectors/base.py", line 110, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/media/pipi/新加卷/IoU-Uniform-R-CNN/mmdet/models/detectors/cascade_rcnn.py", line 966, in simple_test
    det_bboxes, det_labels, _ = bbox_head.get_final_det_bboxes(
  File "/media/pipi/新加卷/anaconda3/envs/IoU-Uniform-R-CNN/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'SharedFCBBoxHead' object has no attribute 'get_final_det_bboxes'

could you send me some solutions ? thank U @zl1994

**Comment by zl1994** [comment]
I have already fixed the bug and refreshed the codes. You can have a try.

**Comment by pipi2020** [comment]
thank U very much !!!
i have try the code which you have refreshed ,it works very well thanks to your highly attention
thanks again. @zl1994
