### ISSUE TITLE
Good paper. Is the paper accepted？

### ISSUE THREAD

**Issue by czy341181** [zl1994/IoU-Uniform-R-CNN#3]
Where is the paper published?   I think this is a very enlightening paper, but I don't see the publish information

**Comment by zl1994** [comment]
Thank you! It was published on Pattern Recognition.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zl1994/IoU-Uniform-R-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 下午3:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zl1994/IoU-Uniform-R-CNN] Good paper. Is the paper accepted？ (#3)





 
Where is the paper published?   I think this is a very enlightening paper, but I don't see the publish information
